### ISSUE TITLE
Naming conventions in python

### ISSUE THREAD

**Issue by dligthart** [BeauvR/blockchain-bse1#1]
Ik zie dat je hier upper case module namen gebruik.

Als tip neem de naming conventies door: https://peps.python.org/pep-0008/

Waarbij:

Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.

Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

https://github.com/BeauvR/blockchain-bse1/blob/01f08a2842039ba3ec2534613e2a52d74dc54868/App.py#L4

**Comment by dligthart** [comment]
https://peps.python.org/pep-0008/#prescriptive-naming-conventions

**Comment by BeauvR** [comment]
Thanks had het inderdaad al opgelost!
